// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pvz/admin_service.proto

package pvzpb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ResizeRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ResizeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResizeRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ResizeRequestMultiError, or
// nil if none found.
func (m *ResizeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ResizeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if val := m.GetSize(); val <= 0 || val > 100 {
		err := ResizeRequestValidationError{
			field:  "Size",
			reason: "value must be inside range (0, 100]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ResizeRequestMultiError(errors)
	}

	return nil
}

// ResizeRequestMultiError is an error wrapping multiple validation errors
// returned by ResizeRequest.ValidateAll() if the designated constraints
// aren't met.
type ResizeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResizeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResizeRequestMultiError) AllErrors() []error { return m }

// ResizeRequestValidationError is the validation error returned by
// ResizeRequest.Validate if the designated constraints aren't met.
type ResizeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResizeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResizeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResizeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResizeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResizeRequestValidationError) ErrorName() string { return "ResizeRequestValidationError" }

// Error satisfies the builtin error interface
func (e ResizeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResizeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResizeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResizeRequestValidationError{}
