// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: pvz/order_service.proto

package pvzpb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AcceptOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Package       *PackageType           `protobuf:"varint,4,opt,name=package,proto3,enum=orders.PackageType,oneof" json:"package,omitempty"`
	Weight        float32                `protobuf:"fixed32,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Price         float32                `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptOrderRequest) Reset() {
	*x = AcceptOrderRequest{}
	mi := &file_pvz_order_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptOrderRequest) ProtoMessage() {}

func (x *AcceptOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_order_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptOrderRequest.ProtoReflect.Descriptor instead.
func (*AcceptOrderRequest) Descriptor() ([]byte, []int) {
	return file_pvz_order_service_proto_rawDescGZIP(), []int{0}
}

func (x *AcceptOrderRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *AcceptOrderRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AcceptOrderRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *AcceptOrderRequest) GetPackage() PackageType {
	if x != nil && x.Package != nil {
		return *x.Package
	}
	return PackageType_PACKAGE_TYPE_UNSPECIFIED
}

func (x *AcceptOrderRequest) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *AcceptOrderRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type OrderIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderIdRequest) Reset() {
	*x = OrderIdRequest{}
	mi := &file_pvz_order_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderIdRequest) ProtoMessage() {}

func (x *OrderIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_order_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderIdRequest.ProtoReflect.Descriptor instead.
func (*OrderIdRequest) Descriptor() ([]byte, []int) {
	return file_pvz_order_service_proto_rawDescGZIP(), []int{1}
}

func (x *OrderIdRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type ProcessOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        ActionType             `protobuf:"varint,2,opt,name=action,proto3,enum=orders.ActionType" json:"action,omitempty"`
	OrderIds      []uint64               `protobuf:"varint,3,rep,packed,name=order_ids,json=orderIds,proto3" json:"order_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessOrdersRequest) Reset() {
	*x = ProcessOrdersRequest{}
	mi := &file_pvz_order_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessOrdersRequest) ProtoMessage() {}

func (x *ProcessOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_order_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessOrdersRequest.ProtoReflect.Descriptor instead.
func (*ProcessOrdersRequest) Descriptor() ([]byte, []int) {
	return file_pvz_order_service_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessOrdersRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ProcessOrdersRequest) GetAction() ActionType {
	if x != nil {
		return x.Action
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

func (x *ProcessOrdersRequest) GetOrderIds() []uint64 {
	if x != nil {
		return x.OrderIds
	}
	return nil
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InPvz         bool                   `protobuf:"varint,2,opt,name=in_pvz,json=inPvz,proto3" json:"in_pvz,omitempty"`
	LastN         *uint32                `protobuf:"varint,3,opt,name=last_n,json=lastN,proto3,oneof" json:"last_n,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,4,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_pvz_order_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_order_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_pvz_order_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListOrdersRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListOrdersRequest) GetInPvz() bool {
	if x != nil {
		return x.InPvz
	}
	return false
}

func (x *ListOrdersRequest) GetLastN() uint32 {
	if x != nil && x.LastN != nil {
		return *x.LastN
	}
	return 0
}

func (x *ListOrdersRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListReturnsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReturnsRequest) Reset() {
	*x = ListReturnsRequest{}
	mi := &file_pvz_order_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReturnsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReturnsRequest) ProtoMessage() {}

func (x *ListReturnsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_order_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReturnsRequest.ProtoReflect.Descriptor instead.
func (*ListReturnsRequest) Descriptor() ([]byte, []int) {
	return file_pvz_order_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListReturnsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ImportOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*AcceptOrderRequest  `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportOrdersRequest) Reset() {
	*x = ImportOrdersRequest{}
	mi := &file_pvz_order_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportOrdersRequest) ProtoMessage() {}

func (x *ImportOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_order_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportOrdersRequest.ProtoReflect.Descriptor instead.
func (*ImportOrdersRequest) Descriptor() ([]byte, []int) {
	return file_pvz_order_service_proto_rawDescGZIP(), []int{5}
}

func (x *ImportOrdersRequest) GetOrders() []*AcceptOrderRequest {
	if x != nil {
		return x.Orders
	}
	return nil
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_pvz_order_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_order_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_pvz_order_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetHistoryRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type DownloadClientReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SortBy        string                 `protobuf:"bytes,1,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadClientReportRequest) Reset() {
	*x = DownloadClientReportRequest{}
	mi := &file_pvz_order_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadClientReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadClientReportRequest) ProtoMessage() {}

func (x *DownloadClientReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_order_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadClientReportRequest.ProtoReflect.Descriptor instead.
func (*DownloadClientReportRequest) Descriptor() ([]byte, []int) {
	return file_pvz_order_service_proto_rawDescGZIP(), []int{7}
}

func (x *DownloadClientReportRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

type OrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        OrderStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=orders.OrderStatus" json:"status,omitempty"`
	OrderId       uint64                 `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_pvz_order_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_order_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_pvz_order_service_proto_rawDescGZIP(), []int{8}
}

func (x *OrderResponse) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *OrderResponse) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type ProcessResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processed     []uint64               `protobuf:"varint,1,rep,packed,name=processed,proto3" json:"processed,omitempty"`
	Errors        []uint64               `protobuf:"varint,2,rep,packed,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessResult) Reset() {
	*x = ProcessResult{}
	mi := &file_pvz_order_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResult) ProtoMessage() {}

func (x *ProcessResult) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_order_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResult.ProtoReflect.Descriptor instead.
func (*ProcessResult) Descriptor() ([]byte, []int) {
	return file_pvz_order_service_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessResult) GetProcessed() []uint64 {
	if x != nil {
		return x.Processed
	}
	return nil
}

func (x *ProcessResult) GetErrors() []uint64 {
	if x != nil {
		return x.Errors
	}
	return nil
}

type OrdersList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrdersList) Reset() {
	*x = OrdersList{}
	mi := &file_pvz_order_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdersList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdersList) ProtoMessage() {}

func (x *OrdersList) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_order_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdersList.ProtoReflect.Descriptor instead.
func (*OrdersList) Descriptor() ([]byte, []int) {
	return file_pvz_order_service_proto_rawDescGZIP(), []int{10}
}

func (x *OrdersList) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *OrdersList) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ReturnsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Returns       []*Order               `protobuf:"bytes,1,rep,name=returns,proto3" json:"returns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnsList) Reset() {
	*x = ReturnsList{}
	mi := &file_pvz_order_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnsList) ProtoMessage() {}

func (x *ReturnsList) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_order_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnsList.ProtoReflect.Descriptor instead.
func (*ReturnsList) Descriptor() ([]byte, []int) {
	return file_pvz_order_service_proto_rawDescGZIP(), []int{11}
}

func (x *ReturnsList) GetReturns() []*Order {
	if x != nil {
		return x.Returns
	}
	return nil
}

type OrderHistoryList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*OrderHistory        `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderHistoryList) Reset() {
	*x = OrderHistoryList{}
	mi := &file_pvz_order_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderHistoryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderHistoryList) ProtoMessage() {}

func (x *OrderHistoryList) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_order_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderHistoryList.ProtoReflect.Descriptor instead.
func (*OrderHistoryList) Descriptor() ([]byte, []int) {
	return file_pvz_order_service_proto_rawDescGZIP(), []int{12}
}

func (x *OrderHistoryList) GetHistory() []*OrderHistory {
	if x != nil {
		return x.History
	}
	return nil
}

type ImportResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Imported      int32                  `protobuf:"varint,1,opt,name=imported,proto3" json:"imported,omitempty"`
	Errors        []uint64               `protobuf:"varint,2,rep,packed,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportResult) Reset() {
	*x = ImportResult{}
	mi := &file_pvz_order_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportResult) ProtoMessage() {}

func (x *ImportResult) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_order_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportResult.ProtoReflect.Descriptor instead.
func (*ImportResult) Descriptor() ([]byte, []int) {
	return file_pvz_order_service_proto_rawDescGZIP(), []int{13}
}

func (x *ImportResult) GetImported() int32 {
	if x != nil {
		return x.Imported
	}
	return 0
}

func (x *ImportResult) GetErrors() []uint64 {
	if x != nil {
		return x.Errors
	}
	return nil
}

type DownloadClientReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        []byte                 `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadClientReportResponse) Reset() {
	*x = DownloadClientReportResponse{}
	mi := &file_pvz_order_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadClientReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadClientReportResponse) ProtoMessage() {}

func (x *DownloadClientReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_order_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadClientReportResponse.ProtoReflect.Descriptor instead.
func (*DownloadClientReportResponse) Descriptor() ([]byte, []int) {
	return file_pvz_order_service_proto_rawDescGZIP(), []int{14}
}

func (x *DownloadClientReportResponse) GetReport() []byte {
	if x != nil {
		return x.Report
	}
	return nil
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=orders.OrderStatus" json:"status,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Weight        float32                `protobuf:"fixed32,5,opt,name=weight,proto3" json:"weight,omitempty"`
	TotalPrice    float32                `protobuf:"fixed32,6,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Package       *PackageType           `protobuf:"varint,7,opt,name=package,proto3,enum=orders.PackageType,oneof" json:"package,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_pvz_order_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_order_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_pvz_order_service_proto_rawDescGZIP(), []int{15}
}

func (x *Order) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Order) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Order) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Order) GetTotalPrice() float32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Order) GetPackage() PackageType {
	if x != nil && x.Package != nil {
		return *x.Package
	}
	return PackageType_PACKAGE_TYPE_UNSPECIFIED
}

type OrderHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=orders.OrderStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderHistory) Reset() {
	*x = OrderHistory{}
	mi := &file_pvz_order_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderHistory) ProtoMessage() {}

func (x *OrderHistory) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_order_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderHistory.ProtoReflect.Descriptor instead.
func (*OrderHistory) Descriptor() ([]byte, []int) {
	return file_pvz_order_service_proto_rawDescGZIP(), []int{16}
}

func (x *OrderHistory) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderHistory) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *OrderHistory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	CountOnPage   uint32                 `protobuf:"varint,2,opt,name=count_on_page,json=countOnPage,proto3" json:"count_on_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_pvz_order_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_order_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_pvz_order_service_proto_rawDescGZIP(), []int{17}
}

func (x *Pagination) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetCountOnPage() uint32 {
	if x != nil {
		return x.CountOnPage
	}
	return 0
}

var File_pvz_order_service_proto protoreflect.FileDescriptor

const file_pvz_order_service_proto_rawDesc = "" +
	"\n" +
	"\x17pvz/order_service.proto\x12\x06orders\x1a\x15pvz/order_types.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xf1\x01\n" +
	"\x12AcceptOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x122\n" +
	"\apackage\x18\x04 \x01(\x0e2\x13.orders.PackageTypeH\x00R\apackage\x88\x01\x01\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x02R\x06weight\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x02R\x05priceB\n" +
	"\n" +
	"\b_package\"+\n" +
	"\x0eOrderIdRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\"x\n" +
	"\x14ProcessOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12*\n" +
	"\x06action\x18\x02 \x01(\x0e2\x12.orders.ActionTypeR\x06action\x12\x1b\n" +
	"\torder_ids\x18\x03 \x03(\x04R\borderIds\"\xb2\x01\n" +
	"\x11ListOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x15\n" +
	"\x06in_pvz\x18\x02 \x01(\bR\x05inPvz\x12\x1a\n" +
	"\x06last_n\x18\x03 \x01(\rH\x00R\x05lastN\x88\x01\x01\x127\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x12.orders.PaginationH\x01R\n" +
	"pagination\x88\x01\x01B\t\n" +
	"\a_last_nB\r\n" +
	"\v_pagination\"\\\n" +
	"\x12ListReturnsRequest\x127\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x12.orders.PaginationH\x00R\n" +
	"pagination\x88\x01\x01B\r\n" +
	"\v_pagination\"I\n" +
	"\x13ImportOrdersRequest\x122\n" +
	"\x06orders\x18\x01 \x03(\v2\x1a.orders.AcceptOrderRequestR\x06orders\"[\n" +
	"\x11GetHistoryRequest\x127\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x12.orders.PaginationH\x00R\n" +
	"pagination\x88\x01\x01B\r\n" +
	"\v_pagination\"6\n" +
	"\x1bDownloadClientReportRequest\x12\x17\n" +
	"\asort_by\x18\x01 \x01(\tR\x06sortBy\"W\n" +
	"\rOrderResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\x0e2\x13.orders.OrderStatusR\x06status\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x04R\aorderId\"E\n" +
	"\rProcessResult\x12\x1c\n" +
	"\tprocessed\x18\x01 \x03(\x04R\tprocessed\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\x04R\x06errors\"I\n" +
	"\n" +
	"OrdersList\x12%\n" +
	"\x06orders\x18\x01 \x03(\v2\r.orders.OrderR\x06orders\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"6\n" +
	"\vReturnsList\x12'\n" +
	"\areturns\x18\x01 \x03(\v2\r.orders.OrderR\areturns\"B\n" +
	"\x10OrderHistoryList\x12.\n" +
	"\ahistory\x18\x01 \x03(\v2\x14.orders.OrderHistoryR\ahistory\"B\n" +
	"\fImportResult\x12\x1a\n" +
	"\bimported\x18\x01 \x01(\x05R\bimported\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\x04R\x06errors\"6\n" +
	"\x1cDownloadClientReportResponse\x12\x16\n" +
	"\x06report\x18\x01 \x01(\fR\x06report\"\x9c\x02\n" +
	"\x05Order\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12+\n" +
	"\x06status\x18\x03 \x01(\x0e2\x13.orders.OrderStatusR\x06status\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x02R\x06weight\x12\x1f\n" +
	"\vtotal_price\x18\x06 \x01(\x02R\n" +
	"totalPrice\x122\n" +
	"\apackage\x18\a \x01(\x0e2\x13.orders.PackageTypeH\x00R\apackage\x88\x01\x01B\n" +
	"\n" +
	"\b_package\"\x91\x01\n" +
	"\fOrderHistory\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.orders.OrderStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"D\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\"\n" +
	"\rcount_on_page\x18\x02 \x01(\rR\vcountOnPage2\xa5\x06\n" +
	"\rOrdersService\x12^\n" +
	"\vAcceptOrder\x12\x1a.orders.AcceptOrderRequest\x1a\x15.orders.OrderResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/orders/accept\x12b\n" +
	"\vReturnOrder\x12\x16.orders.OrderIdRequest\x1a\x15.orders.OrderResponse\"$\x82\xd3\xe4\x93\x02\x1e\"\x1c/v1/orders/{order_id}/return\x12c\n" +
	"\rProcessOrders\x12\x1c.orders.ProcessOrdersRequest\x1a\x15.orders.ProcessResult\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/orders/process\x12O\n" +
	"\n" +
	"ListOrders\x12\x19.orders.ListOrdersRequest\x1a\x12.orders.OrdersList\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/orders\x12Z\n" +
	"\vListReturns\x12\x1a.orders.ListReturnsRequest\x1a\x13.orders.ReturnsList\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/orders/returns\x12]\n" +
	"\n" +
	"GetHistory\x12\x19.orders.GetHistoryRequest\x1a\x18.orders.OrderHistoryList\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/orders/history\x12_\n" +
	"\fImportOrders\x12\x1b.orders.ImportOrdersRequest\x1a\x14.orders.ImportResult\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/orders/import\x12~\n" +
	"\x14DownloadClientReport\x12#.orders.DownloadClientReportRequest\x1a$.orders.DownloadClientReportResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/reports/clientsB\x8f\x02\x92A\xf8\x01\x12\xbe\x01\n" +
	"\x13Order Pick-Up Point\x12]API для управления процессами Пункта Выдачи Заказов\"C\n" +
	"\fEgor Ponyaev\x12\x1dhttps://github.com/epchamp001\x1a\x14epchamp001@gmail.com2\x031.0\x1a\x0elocalhost:8080*\x01\x012\x10application/json:\x10application/jsonZ\x11api/pkg/pvz;pvzpbb\x06proto3"

var (
	file_pvz_order_service_proto_rawDescOnce sync.Once
	file_pvz_order_service_proto_rawDescData []byte
)

func file_pvz_order_service_proto_rawDescGZIP() []byte {
	file_pvz_order_service_proto_rawDescOnce.Do(func() {
		file_pvz_order_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pvz_order_service_proto_rawDesc), len(file_pvz_order_service_proto_rawDesc)))
	})
	return file_pvz_order_service_proto_rawDescData
}

var file_pvz_order_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pvz_order_service_proto_goTypes = []any{
	(*AcceptOrderRequest)(nil),           // 0: orders.AcceptOrderRequest
	(*OrderIdRequest)(nil),               // 1: orders.OrderIdRequest
	(*ProcessOrdersRequest)(nil),         // 2: orders.ProcessOrdersRequest
	(*ListOrdersRequest)(nil),            // 3: orders.ListOrdersRequest
	(*ListReturnsRequest)(nil),           // 4: orders.ListReturnsRequest
	(*ImportOrdersRequest)(nil),          // 5: orders.ImportOrdersRequest
	(*GetHistoryRequest)(nil),            // 6: orders.GetHistoryRequest
	(*DownloadClientReportRequest)(nil),  // 7: orders.DownloadClientReportRequest
	(*OrderResponse)(nil),                // 8: orders.OrderResponse
	(*ProcessResult)(nil),                // 9: orders.ProcessResult
	(*OrdersList)(nil),                   // 10: orders.OrdersList
	(*ReturnsList)(nil),                  // 11: orders.ReturnsList
	(*OrderHistoryList)(nil),             // 12: orders.OrderHistoryList
	(*ImportResult)(nil),                 // 13: orders.ImportResult
	(*DownloadClientReportResponse)(nil), // 14: orders.DownloadClientReportResponse
	(*Order)(nil),                        // 15: orders.Order
	(*OrderHistory)(nil),                 // 16: orders.OrderHistory
	(*Pagination)(nil),                   // 17: orders.Pagination
	(*timestamppb.Timestamp)(nil),        // 18: google.protobuf.Timestamp
	(PackageType)(0),                     // 19: orders.PackageType
	(ActionType)(0),                      // 20: orders.ActionType
	(OrderStatus)(0),                     // 21: orders.OrderStatus
}
var file_pvz_order_service_proto_depIdxs = []int32{
	18, // 0: orders.AcceptOrderRequest.expires_at:type_name -> google.protobuf.Timestamp
	19, // 1: orders.AcceptOrderRequest.package:type_name -> orders.PackageType
	20, // 2: orders.ProcessOrdersRequest.action:type_name -> orders.ActionType
	17, // 3: orders.ListOrdersRequest.pagination:type_name -> orders.Pagination
	17, // 4: orders.ListReturnsRequest.pagination:type_name -> orders.Pagination
	0,  // 5: orders.ImportOrdersRequest.orders:type_name -> orders.AcceptOrderRequest
	17, // 6: orders.GetHistoryRequest.pagination:type_name -> orders.Pagination
	21, // 7: orders.OrderResponse.status:type_name -> orders.OrderStatus
	15, // 8: orders.OrdersList.orders:type_name -> orders.Order
	15, // 9: orders.ReturnsList.returns:type_name -> orders.Order
	16, // 10: orders.OrderHistoryList.history:type_name -> orders.OrderHistory
	21, // 11: orders.Order.status:type_name -> orders.OrderStatus
	18, // 12: orders.Order.expires_at:type_name -> google.protobuf.Timestamp
	19, // 13: orders.Order.package:type_name -> orders.PackageType
	21, // 14: orders.OrderHistory.status:type_name -> orders.OrderStatus
	18, // 15: orders.OrderHistory.created_at:type_name -> google.protobuf.Timestamp
	0,  // 16: orders.OrdersService.AcceptOrder:input_type -> orders.AcceptOrderRequest
	1,  // 17: orders.OrdersService.ReturnOrder:input_type -> orders.OrderIdRequest
	2,  // 18: orders.OrdersService.ProcessOrders:input_type -> orders.ProcessOrdersRequest
	3,  // 19: orders.OrdersService.ListOrders:input_type -> orders.ListOrdersRequest
	4,  // 20: orders.OrdersService.ListReturns:input_type -> orders.ListReturnsRequest
	6,  // 21: orders.OrdersService.GetHistory:input_type -> orders.GetHistoryRequest
	5,  // 22: orders.OrdersService.ImportOrders:input_type -> orders.ImportOrdersRequest
	7,  // 23: orders.OrdersService.DownloadClientReport:input_type -> orders.DownloadClientReportRequest
	8,  // 24: orders.OrdersService.AcceptOrder:output_type -> orders.OrderResponse
	8,  // 25: orders.OrdersService.ReturnOrder:output_type -> orders.OrderResponse
	9,  // 26: orders.OrdersService.ProcessOrders:output_type -> orders.ProcessResult
	10, // 27: orders.OrdersService.ListOrders:output_type -> orders.OrdersList
	11, // 28: orders.OrdersService.ListReturns:output_type -> orders.ReturnsList
	12, // 29: orders.OrdersService.GetHistory:output_type -> orders.OrderHistoryList
	13, // 30: orders.OrdersService.ImportOrders:output_type -> orders.ImportResult
	14, // 31: orders.OrdersService.DownloadClientReport:output_type -> orders.DownloadClientReportResponse
	24, // [24:32] is the sub-list for method output_type
	16, // [16:24] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_pvz_order_service_proto_init() }
func file_pvz_order_service_proto_init() {
	if File_pvz_order_service_proto != nil {
		return
	}
	file_pvz_order_types_proto_init()
	file_pvz_order_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_pvz_order_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_pvz_order_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_pvz_order_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_pvz_order_service_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pvz_order_service_proto_rawDesc), len(file_pvz_order_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pvz_order_service_proto_goTypes,
		DependencyIndexes: file_pvz_order_service_proto_depIdxs,
		MessageInfos:      file_pvz_order_service_proto_msgTypes,
	}.Build()
	File_pvz_order_service_proto = out.File
	file_pvz_order_service_proto_goTypes = nil
	file_pvz_order_service_proto_depIdxs = nil
}
