// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: pvz/order_types.proto

package pvzpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionType int32

const (
	ActionType_ACTION_TYPE_UNSPECIFIED ActionType = 0
	ActionType_ACTION_TYPE_ISSUE       ActionType = 1
	ActionType_ACTION_TYPE_RETURN      ActionType = 2
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ACTION_TYPE_UNSPECIFIED",
		1: "ACTION_TYPE_ISSUE",
		2: "ACTION_TYPE_RETURN",
	}
	ActionType_value = map[string]int32{
		"ACTION_TYPE_UNSPECIFIED": 0,
		"ACTION_TYPE_ISSUE":       1,
		"ACTION_TYPE_RETURN":      2,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_pvz_order_types_proto_enumTypes[0].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_pvz_order_types_proto_enumTypes[0]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_pvz_order_types_proto_rawDescGZIP(), []int{0}
}

type PackageType int32

const (
	PackageType_PACKAGE_TYPE_UNSPECIFIED PackageType = 0
	PackageType_PACKAGE_TYPE_BAG         PackageType = 1
	PackageType_PACKAGE_TYPE_BOX         PackageType = 2
	PackageType_PACKAGE_TYPE_TAPE        PackageType = 3
	PackageType_PACKAGE_TYPE_BAG_TAPE    PackageType = 4
	PackageType_PACKAGE_TYPE_BOX_TAPE    PackageType = 5
)

// Enum value maps for PackageType.
var (
	PackageType_name = map[int32]string{
		0: "PACKAGE_TYPE_UNSPECIFIED",
		1: "PACKAGE_TYPE_BAG",
		2: "PACKAGE_TYPE_BOX",
		3: "PACKAGE_TYPE_TAPE",
		4: "PACKAGE_TYPE_BAG_TAPE",
		5: "PACKAGE_TYPE_BOX_TAPE",
	}
	PackageType_value = map[string]int32{
		"PACKAGE_TYPE_UNSPECIFIED": 0,
		"PACKAGE_TYPE_BAG":         1,
		"PACKAGE_TYPE_BOX":         2,
		"PACKAGE_TYPE_TAPE":        3,
		"PACKAGE_TYPE_BAG_TAPE":    4,
		"PACKAGE_TYPE_BOX_TAPE":    5,
	}
)

func (x PackageType) Enum() *PackageType {
	p := new(PackageType)
	*p = x
	return p
}

func (x PackageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackageType) Descriptor() protoreflect.EnumDescriptor {
	return file_pvz_order_types_proto_enumTypes[1].Descriptor()
}

func (PackageType) Type() protoreflect.EnumType {
	return &file_pvz_order_types_proto_enumTypes[1]
}

func (x PackageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackageType.Descriptor instead.
func (PackageType) EnumDescriptor() ([]byte, []int) {
	return file_pvz_order_types_proto_rawDescGZIP(), []int{1}
}

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_ORDER_STATUS_EXPECTS     OrderStatus = 1
	OrderStatus_ORDER_STATUS_ACCEPTED    OrderStatus = 2
	OrderStatus_ORDER_STATUS_RETURNED    OrderStatus = 3
	OrderStatus_ORDER_STATUS_DELETED     OrderStatus = 4
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_EXPECTS",
		2: "ORDER_STATUS_ACCEPTED",
		3: "ORDER_STATUS_RETURNED",
		4: "ORDER_STATUS_DELETED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"ORDER_STATUS_EXPECTS":     1,
		"ORDER_STATUS_ACCEPTED":    2,
		"ORDER_STATUS_RETURNED":    3,
		"ORDER_STATUS_DELETED":     4,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pvz_order_types_proto_enumTypes[2].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_pvz_order_types_proto_enumTypes[2]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_pvz_order_types_proto_rawDescGZIP(), []int{2}
}

var File_pvz_order_types_proto protoreflect.FileDescriptor

const file_pvz_order_types_proto_rawDesc = "" +
	"\n" +
	"\x15pvz/order_types.proto\x12\x06orders*X\n" +
	"\n" +
	"ActionType\x12\x1b\n" +
	"\x17ACTION_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ACTION_TYPE_ISSUE\x10\x01\x12\x16\n" +
	"\x12ACTION_TYPE_RETURN\x10\x02*\xa4\x01\n" +
	"\vPackageType\x12\x1c\n" +
	"\x18PACKAGE_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10PACKAGE_TYPE_BAG\x10\x01\x12\x14\n" +
	"\x10PACKAGE_TYPE_BOX\x10\x02\x12\x15\n" +
	"\x11PACKAGE_TYPE_TAPE\x10\x03\x12\x19\n" +
	"\x15PACKAGE_TYPE_BAG_TAPE\x10\x04\x12\x19\n" +
	"\x15PACKAGE_TYPE_BOX_TAPE\x10\x05*\x95\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_EXPECTS\x10\x01\x12\x19\n" +
	"\x15ORDER_STATUS_ACCEPTED\x10\x02\x12\x19\n" +
	"\x15ORDER_STATUS_RETURNED\x10\x03\x12\x18\n" +
	"\x14ORDER_STATUS_DELETED\x10\x04B\x13Z\x11api/pkg/pvz;pvzpbb\x06proto3"

var (
	file_pvz_order_types_proto_rawDescOnce sync.Once
	file_pvz_order_types_proto_rawDescData []byte
)

func file_pvz_order_types_proto_rawDescGZIP() []byte {
	file_pvz_order_types_proto_rawDescOnce.Do(func() {
		file_pvz_order_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pvz_order_types_proto_rawDesc), len(file_pvz_order_types_proto_rawDesc)))
	})
	return file_pvz_order_types_proto_rawDescData
}

var file_pvz_order_types_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pvz_order_types_proto_goTypes = []any{
	(ActionType)(0),  // 0: orders.ActionType
	(PackageType)(0), // 1: orders.PackageType
	(OrderStatus)(0), // 2: orders.OrderStatus
}
var file_pvz_order_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pvz_order_types_proto_init() }
func file_pvz_order_types_proto_init() {
	if File_pvz_order_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pvz_order_types_proto_rawDesc), len(file_pvz_order_types_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pvz_order_types_proto_goTypes,
		DependencyIndexes: file_pvz_order_types_proto_depIdxs,
		EnumInfos:         file_pvz_order_types_proto_enumTypes,
	}.Build()
	File_pvz_order_types_proto = out.File
	file_pvz_order_types_proto_goTypes = nil
	file_pvz_order_types_proto_depIdxs = nil
}
