{
 "title": "PVZ Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "RPS Time Series",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Всего выдано заказов",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pvz_orders_issued_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Всего принято заказов",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pvz_orders_accepted_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Всего возвращено заказов",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pvz_orders_returned_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Выселение кэша в течении часа",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(pvz_cache_evictions_total[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Errors Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_errors_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}