logging:
  mode: "dev"         # dev | prod
  level: "debug"              # debug|info|warn|error|…
  encoding: "console"           # console|json

  sampling: null
  initialFields: {}

  disableCaller: true       # true = убрать caller из логов
  disableStacktrace: true   # true = отключить stacktrace на Error+

  outputPaths:
    - "stdout"

  errorOutputPaths:
    - "stderr"

  timestampKey: "ts"         # вместо "timestamp"
  capitalizeLevel: true      # цветной, заглавный level encoder

grpc_server:
  enable: true
  endpoint: "0.0.0.0"
  port: 8081
  shutdown_timeout: 30

gateway:
  port: 8080
  endpoint: "0.0.0.0"

storage:
  postgres:
    master:
      host: "${PG_HOST}"
      port: ${PG_MASTER_PORT}
    replicas:
      - host: "${PG_HOST}"
        port: 5433          # первая реплика
      - host: "${PG_HOST}"
        port: 5434          # вторая реплика

    database: "${PG_DATABASE}"
    username: "${PG_SUPER_USER}"
    password: "${PG_SUPER_PASSWORD}"
    ssl_mode: "disable"
    connection_attempts: 3

    pool:
      max_connections: 50
      min_connections: 20
      max_lifetime: 3600
      max_idle_time: 300
      health_check_period: 30

workers:
  start: 8
  queue: 128

admin:
  user: "${ADMIN_USER}"
  pass: "${ADMIN_PASS}"

kafka:
  brokers:
    - "localhost:9092"
  topic: "pvz.events-log"

outbox:
  batch_size: 100
  interval: "1s"

cache:
  capacity: 10000
  ttl: "5m"